function gen_readme()
%
% Generate README.md from BatchOffset.csv and CruiseBatch.csv
%
fid = fopen('README.md', 'w');
if fid < 0
    msg = ferror(fid);
    error(['gen_readme.m: cannot open README.md ', msg]);
end
fprintf(fid, '# Salinity batch-to-batch offset of standard seawater\n\n');
fprintf(fid, '*This `README.md` is automatically generated from `BatchOffset.csv`. DO not edit this file. Instead, edit the CSV file and use Matlab;*\n');
fprintf(fid, '~~~\n');
fprintf(fid, '%% To generate README.md\n');
fprintf(fid, '>> gen_readme\n');
fprintf(fid, '~~~\n');
fprintf(fid, 'The batch-to-batch table is available with DOI:[10.17596/0001983](https://dx.doi.org/10.17596/0001983)\n');
%
fprintf(fid, '## Cruise and batch\n');
fprintf(fid, 'Undocumented batch numbers are from Purkey through personal communication.\n');
csv2md('CruiseBatch.csv', fid, '|:--|--:|:--|:--|:--|\n');
%
fclose(fid);
end
