function gen_readme()
%
% Generate README.md from BatchOffset.csv and CruiseBatch.csv
%
fid = fopen('README.md', 'w');
if fid < 0
    msg = ferror(fid);
    error(['gen_readme.m: cannot open README.md ', msg]);
end
fprintf(fid, '# Salinity batch-to-batch offset of standard seawater\n\n');
fprintf(fid, '*This `README.md` is automatically generated from `BatchOffset.csv` and `CruiseBatch.csv`. DO not edit this file. Instead, edit the CSV files and use Matlab;*\n');
fprintf(fid, '~~~\n');
fprintf(fid, '%% To generate README.md\n');
fprintf(fid, '>> gen_readme\n');
fprintf(fid, '~~~\n');
fprintf(fid, 'The tables are update of Table 6 in [Kawano *et al.* (2006)](https://doi.org/10.1007/s10872-006-0097-8) and Table A1 in [Purkey and Johnson (2013)](https://doi.org/10.1175/JCLI-D-12-00834.1).\n');
fprintf(fid, 'Latest table is available from JAMTEC''s [Post-WOCE Hydrograph](http://www.jamstec.go.jp/iorgc/ocorp/data/post-woce.html) page, e.g. Table A1 of [Uchida *et al.* (2018)](http://www.jamstec.go.jp/iorgc/ocorp/data/i10rev_2015/book/i10rev_2015_databook.pdf)\n');
%
fprintf(fid, '## Batch and offset\n');
csv2md('BatchOffset.csv', fid, '|:--|--:|\n');

fprintf(fid, '## Cruise and batch\n');
csv2md('CruiseBatch.csv', fid, '|:--|--:|:--|:--|:--|\n');
%
fclose(fid);
end
